output "server_ips" {
  description = "IP address of each server, keyed by role"
  value       = { for role, server in module.app_server : role => server.ip }
}

output "ssh_commands" {
  description = "Copy-paste SSH command for each server"
  value = {
    for role, server in module.app_server :
    role => "ssh -i ${var.ssh_private_key_path} ${var.ssh_user}@${server.ip}"
  }
}

output "ansible_inventory" {
  description = "Ansible inventory in INI format; pipeline.sh writes this to ansible/inventory.ini"
  value = join("\n", concat(
    [
      "# GENERATED by pipeline.sh from terraform output - do not edit by hand",
      "[kijanikiosk]",
    ],
    [
      for role, server in module.app_server :
      "${server.name} ansible_host=${server.ip} server_role=${role}"
    ],
    [""]
  ))
}
